- hosts: all
  tasks: 

  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache
    service:
      name: httpd
      state: started

  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes


  - name: Install wget
    yum:
      name: wget
      state: latest

  - name: Install unzip
    yum:
      name: unzip
      state: latest

  - name: download templates
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page258/highway.zip
      dest: /var/www/html

  - name: unzip
    unarchive: 
      src: /var/www/html/highway.zip
      dest: /var/www/html/
      remote_src: yes

  - name: move files
    shell: rsync -r /var/www/html/templatemo_520_highway /var/www/html