- hosts: all
  tasks: 
  
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache
    service:
      name: httpd
      state: started

  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes